-- Database: mfe_citi

-- DROP DATABASE mfe_citi;

CREATE DATABASE mfe_citi
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE mfe_citi TO postgres;
GRANT ALL ON DATABASE mfe_citi TO mfe_citi;
REVOKE ALL ON DATABASE mfe_citi FROM public;

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO mfe_citi;

